repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.36.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.3.0
        files: \.(js|jsx|ts|tsx)$
        types: [file]

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier
        language: node
        types_or: [file]
        files: \.(js|jsx|ts|tsx|json|css|scss|md|yaml|yml)$
        args: ["--write"]
